
version: 2

models:
  - name: lang_popularity_source
    description: "A starter dbt model"
    columns:
      - name: rust_popularity
        description: "The primary use for this table"
        tests:
          - not_null
