# example profiles.yml file
playground:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: example
      port: 5432
      dbname: playground
      schema: dbt_playground
      threads: 4